/**
 * Todos los municipios de Colombia — fuente: DANE 2024
 * Ordenados alfabéticamente. Municipios con nombre duplicado en varios
 * departamentos incluyen el departamento entre paréntesis.
 */
export const MUNICIPIOS_COLOMBIA = [
  "Ábrego",
  "Abejorral",
  "Abriaquí",
  "Acacías",
  "Acandí",
  "Acevedo",
  "Achí",
  "Agua de Dios",
  "Aguachica",
  "Aguada",
  "Aguadas",
  "Aguazul",
  "Agustín Codazzi",
  "Aipe",
  "Albán (Cundinamarca)",
  "Albán (Nariño)",
  "Albania (Caquetá)",
  "Albania (La Guajira)",
  "Albania (Santander)",
  "Alcalá",
  "Aldana",
  "Alejandría",
  "Algeciras",
  "Algarrobo",
  "Almaguer",
  "Almeida",
  "Alpujarra",
  "Altamira",
  "Altos del Rosario",
  "Alvarado",
  "Amagá",
  "Amalfi",
  "Ambalema",
  "Anapoima",
  "Ancuyá",
  "Andes",
  "Andalucía",
  "Angelópolis",
  "Angostura",
  "Anolaima",
  "Anorí",
  "Anserma",
  "Ansermanuevo",
  "Anzoátegui",
  "Anzá",
  "Apartadó",
  "Apía",
  "Apulo",
  "Aquitania",
  "Aracataca",
  "Arauca",
  "Arauquita",
  "Arbeláez",
  "Arboleda",
  "Arboletes",
  "Arboledas",
  "Arcabuco",
  "Argelia (Antioquia)",
  "Argelia (Cauca)",
  "Argelia (Valle del Cauca)",
  "Ariguaní",
  "Arjona",
  "Armenia (Antioquia)",
  "Armenia (Quindío)",
  "Armero-Guayabal",
  "Arroyohondo",
  "Astrea",
  "Ataco",
  "Atrato",
  "Ayapel",
  "Bagadó",
  "Bahía Solano",
  "Bajo Baudó",
  "Balboa (Cauca)",
  "Balboa (Risaralda)",
  "Baranoa",
  "Baraya",
  "Barbacoas",
  "Barbosa (Antioquia)",
  "Barbosa (Santander)",
  "Barichara",
  "Barranca de Upía",
  "Barrancabermeja",
  "Barrancas",
  "Barranco de Loba",
  "Barranco Minas",
  "Barranquilla",
  "Becerril",
  "Belalcázar",
  "Belén (Boyacá)",
  "Belén (Nariño)",
  "Belén de los Andaquíes",
  "Belén de Umbría",
  "Bello",
  "Beltrán",
  "Berbeo",
  "Betéitiva",
  "Betania",
  "Betulia (Antioquia)",
  "Betulia (Santander)",
  "Bituima",
  "Boavita",
  "Bogotá",
  "Bojacá",
  "Bojayá",
  "Bolívar (Cauca)",
  "Bolívar (Santander)",
  "Bolívar (Valle del Cauca)",
  "Bosconia",
  "Briceño (Antioquia)",
  "Briceño (Boyacá)",
  "Bucaramanga",
  "Bucarasica",
  "Buenaventura",
  "Buenavista (Boyacá)",
  "Buenavista (Córdoba)",
  "Buenavista (Quindío)",
  "Buenavista (Sucre)",
  "Buesaco",
  "Bugalagrande",
  "Buriticá",
  "Busbanzá",
  "Cabrera (Cundinamarca)",
  "Cabrera (Santander)",
  "Cabuyaro",
  "Cáceres",
  "Cáchira",
  "Cácota",
  "Caicedonia",
  "Caicedo",
  "Cajamarca",
  "Cajibío",
  "Cajicá",
  "Calamar (Bolívar)",
  "Calamar (Guaviare)",
  "Calarcá",
  "Caldas (Antioquia)",
  "Caldas (Boyacá)",
  "Caldono",
  "Cali",
  "California",
  "Calima",
  "Caloto",
  "Campo de la Cruz",
  "Campoalegre",
  "Campamento",
  "Campohermoso",
  "Canalete",
  "Candelaria (Atlántico)",
  "Candelaria (Valle del Cauca)",
  "Cañasgordas",
  "Caparrapí",
  "Capitanejo",
  "Cáqueza",
  "Caracolí",
  "Caramanta",
  "Carcasí",
  "Carepa",
  "Carmen de Apicalá",
  "Carmen de Carupa",
  "Carmen de Viboral",
  "Carmen del Darién",
  "Cartagena",
  "Cartagena del Chairá",
  "Cartago",
  "Carurú",
  "Casabianca",
  "Castilla la Nueva",
  "Caucasia",
  "Cepitá",
  "Cereté",
  "Cerrito",
  "Cerro de San Antonio",
  "Cértegui",
  "Chaparral",
  "Chachagüí",
  "Chalán",
  "Chameza",
  "Chaguaní",
  "Charalá",
  "Charta",
  "Chía",
  "Chibolo",
  "Chigorodó",
  "Chimá",
  "Chima (Santander)",
  "Chimichagua",
  "Chinácota",
  "Chinchiná",
  "Chipatá",
  "Chipaque",
  "Chiriguaná",
  "Chitagá",
  "Chivatá",
  "Chíquiza",
  "Chiquinquirá",
  "Chiscas",
  "Chitaraque",
  "Chivor",
  "Choachí",
  "Chocontá",
  "Ciénaga",
  "Ciénega",
  "Ciénaga de Oro",
  "Cimitarra",
  "Circasia",
  "Cisneros",
  "Clemencia",
  "Cocorná",
  "Coello",
  "Cogua",
  "Colón (Nariño)",
  "Colón (Putumayo)",
  "Colombia",
  "Colosó",
  "Cómbita",
  "Concepción (Antioquia)",
  "Concepción (Santander)",
  "Concordia (Antioquia)",
  "Concordia (Magdalena)",
  "Condoto",
  "Confines",
  "Consacá",
  "Contadero",
  "Contratación",
  "Convención",
  "Coper",
  "Copacabana",
  "Córdoba (Bolívar)",
  "Córdoba (Nariño)",
  "Córdoba (Quindío)",
  "Corinto",
  "Coromoro",
  "Corrales",
  "Cota",
  "Cotorra",
  "Covarachía",
  "Coyaima",
  "Cravo Norte",
  "Cubará",
  "Cucaita",
  "Cubarral",
  "Cuítiva",
  "Cumaribo",
  "Cumaral",
  "Cunday",
  "Curumaní",
  "Curití",
  "Curillo",
  "Dabeiba",
  "Dagua",
  "Dibulla",
  "Distracción",
  "Dolores",
  "Don Matías",
  "Dosquebradas",
  "Durania",
  "Ebéjico",
  "El Águila",
  "El Bagre",
  "El Cairo",
  "El Calvario",
  "El Cantón de San Pablo",
  "El Carmen de Atrato",
  "El Carmen de Bolívar",
  "El Carmen de Chucurí",
  "El Carmen (Norte de Santander)",
  "El Castillo",
  "El Cerrito",
  "El Charco",
  "El Cocuy",
  "El Colegio",
  "El Copey",
  "El Doncello",
  "El Dorado",
  "El Dovio",
  "El Espino",
  "El Guacamayo",
  "El Guamo",
  "El Litoral del San Juan",
  "El Molino",
  "El Paso",
  "El Paujil",
  "El Peñol (Antioquia)",
  "El Peñón (Bolívar)",
  "El Peñón (Cundinamarca)",
  "El Peñón (Santander)",
  "El Peñol (Nariño)",
  "El Piñón",
  "El Playón",
  "El Retiro",
  "El Retén",
  "El Retorno",
  "El Roble",
  "El Rosal",
  "El Rosario",
  "El Tablón de Gómez",
  "El Tambo (Cauca)",
  "El Tambo (Nariño)",
  "El Tarra",
  "El Zulia",
  "Elías",
  "Encino",
  "Enciso",
  "Entrerríos",
  "Envigado",
  "Espinal",
  "Facatativá",
  "Falan",
  "Filadelfia",
  "Filandia",
  "Firavitoba",
  "Flandes",
  "Florencia",
  "Florencia (Cauca)",
  "Floresta",
  "Florián",
  "Floridablanca",
  "Florida",
  "Fomeque",
  "Fonseca",
  "Fortul",
  "Fosca",
  "Francisco Pizarro",
  "Fredonia",
  "Fresno",
  "Frontino",
  "Fundación",
  "Funza",
  "Fúquene",
  "Fusagasugá",
  "Funes",
  "Gachalá",
  "Gachancipá",
  "Gachetá",
  "Gachantivá",
  "Galapa",
  "Galeras",
  "Gálan",
  "Gama",
  "Gambita",
  "Gameza",
  "Garagoa",
  "Garzón",
  "Génova",
  "Gigante",
  "Ginebra",
  "Giraldo",
  "Girardot",
  "Girardota",
  "Girón",
  "Gómez Plata",
  "González",
  "Gramalote",
  "Granada (Antioquia)",
  "Granada (Cundinamarca)",
  "Granada (Meta)",
  "Guadalajara de Buga",
  "Guadalupe (Antioquia)",
  "Guadalupe (Huila)",
  "Guadalupe (Santander)",
  "Guacamayas",
  "Guachetá",
  "Guachucal",
  "Guacarí",
  "Guaduas",
  "Guaitarilla",
  "Gualmatán",
  "Guamal (Magdalena)",
  "Guamal (Meta)",
  "Guamo",
  "Guapi",
  "Guaranda",
  "Guarne",
  "Guasca",
  "Guataquí",
  "Guatapé",
  "Guatavita",
  "Guayabal de Síquima",
  "Guayabetal",
  "Guática",
  "Güepsa",
  "Gutiérrez",
  "Güicán de la Sierra",
  "Hacarí",
  "Hatillo de Loba",
  "Hato Corozal",
  "Hatonuevo",
  "Heliconia",
  "Herrán",
  "Herveo",
  "Hispania",
  "Hobo",
  "Honda",
  "Ibagué",
  "Icononzo",
  "Iles",
  "Imués",
  "Inírida",
  "Inzá",
  "Ipiales",
  "Iquira",
  "Isnos",
  "Itagüí",
  "Ituango",
  "Iza",
  "Jambaló",
  "Jamundí",
  "Jardín",
  "Jenesano",
  "Jericó (Antioquia)",
  "Jericó (Boyacá)",
  "Jerusalén",
  "Jesús María",
  "Juan de Acosta",
  "Juradó",
  "Junín",
  "La Apartada",
  "La Argentina",
  "La Belleza",
  "La Calera",
  "La Capilla",
  "La Ceja",
  "La Celia",
  "La Cruz",
  "La Cumbre",
  "La Dorada",
  "La Esperanza",
  "La Estrella",
  "La Florida",
  "La Gloria",
  "La Jagua de Ibirico",
  "La Jagua del Pilar",
  "La Llanada",
  "La Macarena",
  "La Mesa",
  "La Merced",
  "La Montañita",
  "La Palma",
  "La Paz (Cesar)",
  "La Paz (Santander)",
  "La Peña",
  "La Pintada",
  "La Plata",
  "La Playa de Belén",
  "La Primavera",
  "La Salina",
  "La Sierra",
  "La Tola",
  "La Unión (Antioquia)",
  "La Unión (Nariño)",
  "La Unión (Sucre)",
  "La Unión (Valle del Cauca)",
  "La Uribe",
  "La Uvita",
  "La Vega (Cauca)",
  "La Vega (Cundinamarca)",
  "La Victoria (Boyacá)",
  "La Victoria (Valle del Cauca)",
  "La Virginia",
  "Labateca",
  "Labranzagrande",
  "Landázuri",
  "Lebrija",
  "Leiva",
  "Lejanías",
  "Lenguazaque",
  "Lérida",
  "Leticia",
  "Líbano",
  "Liborina",
  "Linares",
  "Lloró",
  "Lorica",
  "Los Andes",
  "Los Córdobas",
  "Los Palmitos",
  "Los Patios",
  "Los Santos",
  "Lourdes",
  "Luruaco",
  "Maceo",
  "Machetá",
  "Macanal",
  "Macaravita",
  "Maicao",
  "Madrid",
  "Magangué",
  "Magüí Payán",
  "Mahates",
  "Majagual",
  "Málaga",
  "Malambo",
  "Manatí",
  "Manaure",
  "Manaure Balcón del Cesar",
  "Maní",
  "Manizales",
  "Manta",
  "Mapiripán",
  "Marinilla",
  "Maripí",
  "Mariquita",
  "Marmato",
  "Marquetalia",
  "Marsella",
  "Marulanda",
  "Matanza",
  "Medellín",
  "Medina",
  "Melgar",
  "Mercaderes",
  "Mesetas",
  "Milán",
  "Miraflores (Boyacá)",
  "Miraflores (Guaviare)",
  "Miranda",
  "Mistrató",
  "Mitú",
  "Mocoa",
  "Mogotes",
  "Molagavita",
  "Momil",
  "Mompós",
  "Montenegro",
  "Montebello",
  "Montecristo",
  "Montelíbano",
  "Montería",
  "Monterrey",
  "Morales (Bolívar)",
  "Morales (Cauca)",
  "Morelia",
  "Moñitos",
  "Mosquera (Cundinamarca)",
  "Mosquera (Nariño)",
  "Murillo",
  "Murindó",
  "Mutatá",
  "Muzo",
  "Nariño (Antioquia)",
  "Nariño (Cundinamarca)",
  "Natagaima",
  "Nátaga",
  "Nechí",
  "Necoclí",
  "Neira",
  "Nemocón",
  "Nilo",
  "Nimaima",
  "Nobsa",
  "Nocaima",
  "Norcasia",
  "Norosí",
  "Nóvita",
  "Nueva Granada",
  "Nuevo Colón",
  "Obando",
  "Ocamonte",
  "Ocaña",
  "Oiba",
  "Oicatá",
  "Olaya",
  "Olaya Herrera",
  "Onzaga",
  "Oporapa",
  "Orito",
  "Ortega",
  "Otanche",
  "Ovejas",
  "Pachavita",
  "Pacho",
  "Paicol",
  "Paime",
  "Paipa",
  "Pajarito",
  "Palermo",
  "Palmar de Varela",
  "Palmas del Socorro",
  "Palmira",
  "Palmito",
  "Palocabildo",
  "Palestina (Caldas)",
  "Palestina (Huila)",
  "Pandi",
  "Panqueba",
  "Paratebueno",
  "Páramo",
  "Pasca",
  "Pasto",
  "Pauna",
  "Paya",
  "Paz de Ariporo",
  "Paz de Río",
  "Pedraza",
  "Pensilvania",
  "Peque",
  "Pereira",
  "Pesca",
  "Piedecuesta",
  "Piedras",
  "Piendamó",
  "Pijiño del Carmen",
  "Pijao",
  "Piojó",
  "Pital",
  "Pitalito",
  "Pivijay",
  "Planeta Rica",
  "Planadas",
  "Plato",
  "Polonuevo",
  "Ponedera",
  "Popayán",
  "Potosí",
  "Prado",
  "Providencia (Nariño)",
  "Providencia (San Andrés)",
  "Pueblo Bello",
  "Pueblo Nuevo",
  "Pueblo Rico",
  "Pueblorrico",
  "Puebloviejo",
  "Puente Nacional",
  "Puerto Asís",
  "Puerto Berrío",
  "Puerto Boyacá",
  "Puerto Caicedo",
  "Puerto Carreño",
  "Puerto Colombia",
  "Puerto Concordia",
  "Puerto Escondido",
  "Puerto Gaitán",
  "Puerto Guzmán",
  "Puerto Leguízamo",
  "Puerto Libertador",
  "Puerto Lleras",
  "Puerto López",
  "Puerto Nare",
  "Puerto Nariño",
  "Puerto Rico (Caquetá)",
  "Puerto Rico (Meta)",
  "Puerto Rondón",
  "Puerto Salgar",
  "Puerto Santander",
  "Puerto Tejada",
  "Puerto Triunfo",
  "Puerto Wilches",
  "Pulí",
  "Pupiales",
  "Puracé",
  "Purificación",
  "Purísima",
  "Puerres",
  "Quebradanegra",
  "Quetame",
  "Quibdó",
  "Quimbaya",
  "Quinchía",
  "Quipile",
  "Quípama",
  "Ragonvalia",
  "Ramiriquí",
  "Ráquira",
  "Recetor",
  "Regidor",
  "Remedios",
  "Remolino",
  "Restrepo (Meta)",
  "Restrepo (Valle del Cauca)",
  "Ricaurte (Cundinamarca)",
  "Ricaurte (Nariño)",
  "Río de Oro",
  "Río Iró",
  "Río Quito",
  "Río Viejo",
  "Rioblanco",
  "Riofrío",
  "Rionegro (Antioquia)",
  "Rionegro (Santander)",
  "Riosucio (Caldas)",
  "Riosucio (Chocó)",
  "Risaralda",
  "Rivera",
  "Roberto Payán",
  "Roldanillo",
  "Roncesvalles",
  "Rondón",
  "Rosas",
  "Rovira",
  "Sabana de Torres",
  "Sabanagrande",
  "Sabanalarga (Antioquia)",
  "Sabanalarga (Atlántico)",
  "Sabanalarga (Casanare)",
  "Sabaneta",
  "Saboyá",
  "Sácama",
  "Sáchica",
  "Sahagún",
  "Saladoblanco",
  "Saldaña",
  "Salazar",
  "Salento",
  "Salgar",
  "Salamina (Caldas)",
  "Salamina (Magdalena)",
  "Samacá",
  "Sampués",
  "San Agustín",
  "San Alberto",
  "San Andrés (San Andrés y Providencia)",
  "San Andrés (Santander)",
  "San Andrés de Cuerquia",
  "San Andrés de Sotavento",
  "San Antonio",
  "San Antero",
  "San Benito",
  "San Benito Abad",
  "San Bernardo (Cundinamarca)",
  "San Bernardo (Nariño)",
  "San Bernardo del Viento",
  "San Calixto",
  "San Carlos (Antioquia)",
  "San Carlos (Córdoba)",
  "San Carlos de Guaroa",
  "San Cayetano (Cundinamarca)",
  "San Cayetano (Norte de Santander)",
  "San Eduardo",
  "San Estanislao",
  "San Fernando",
  "San Francisco (Antioquia)",
  "San Francisco (Cundinamarca)",
  "San Francisco (Putumayo)",
  "San Gil",
  "San Jacinto",
  "San Jacinto del Cauca",
  "San Jerónimo",
  "San Joaquín",
  "San José (Caldas)",
  "San José de la Montaña",
  "San José de Miranda",
  "San José de Pare",
  "San José de Uré",
  "San José del Fragua",
  "San José del Guaviare",
  "San José del Palmar",
  "San Juan de Arama",
  "San Juan de Betulia",
  "San Juan de Rioseco",
  "San Juan de Urabá",
  "San Juan del Cesar",
  "San Juan Nepomuceno",
  "San Juanito",
  "San Lorenzo",
  "San Luis (Antioquia)",
  "San Luis (Tolima)",
  "San Luis de Gaceno",
  "San Luis de Palenque",
  "San Marcos",
  "San Martín (Cesar)",
  "San Martín (Meta)",
  "San Martín de Loba",
  "San Mateo",
  "San Miguel (Putumayo)",
  "San Miguel (Santander)",
  "San Miguel de Sema",
  "San Onofre",
  "San Pablo (Bolívar)",
  "San Pablo (Nariño)",
  "San Pablo de Borbur",
  "San Pedro (Sucre)",
  "San Pedro (Valle del Cauca)",
  "San Pedro de Cartago",
  "San Pedro de los Milagros",
  "San Pedro de Urabá",
  "San Pelayo",
  "San Rafael",
  "San Roque",
  "San Sebastián",
  "San Sebastián de Buenavista",
  "San Vicente de Chucurí",
  "San Vicente del Caguán",
  "San Vicente Ferrer",
  "San Zenón",
  "Sandoná",
  "Santa Ana",
  "Santa Bárbara (Antioquia)",
  "Santa Bárbara (Nariño)",
  "Santa Bárbara (Santander)",
  "Santa Bárbara de Pinto",
  "Santa Catalina",
  "Santa Helena del Opón",
  "Santa Isabel",
  "Santa Lucía",
  "Santa María (Boyacá)",
  "Santa María (Huila)",
  "Santa Marta",
  "Santa Rosa (Bolívar)",
  "Santa Rosa (Cauca)",
  "Santa Rosa de Cabal",
  "Santa Rosa de Osos",
  "Santa Rosa de Viterbo",
  "Santa Rosa del Sur",
  "Santa Rosalía",
  "Santa Sofía",
  "Santacruz",
  "Santana",
  "Santander de Quilichao",
  "Santiago (Norte de Santander)",
  "Santiago (Putumayo)",
  "Santo Domingo",
  "Santo Tomás",
  "Santuario (Antioquia)",
  "Santuario (Risaralda)",
  "Sapuyes",
  "Saravena",
  "Sardinata",
  "Sasaima",
  "Sativanorte",
  "Sativasur",
  "Segovia",
  "Sesquilé",
  "Sevilla",
  "Siachoque",
  "Sibaté",
  "Sibundoy",
  "Silos",
  "Silvania",
  "Silvia",
  "Simacota",
  "Simijaca",
  "Simití",
  "Sipí",
  "Sitionuevo",
  "Soatá",
  "Socha",
  "Socotá",
  "Sogamoso",
  "Solano",
  "Soledad",
  "Solita",
  "Somondoco",
  "Sonsón",
  "Sopetrán",
  "Soplaviento",
  "Sopó",
  "Sora",
  "Soracá",
  "Sotaquirá",
  "Suan",
  "Suárez (Cauca)",
  "Suárez (Tolima)",
  "Suaita",
  "Subachoque",
  "Sucre (Cauca)",
  "Sucre (Santander)",
  "Sucre (Sucre)",
  "Suesca",
  "Supatá",
  "Supía",
  "Susa",
  "Susacón",
  "Sutamarchán",
  "Sutatenza",
  "Tabio",
  "Tadó",
  "Talaigua Nuevo",
  "Támara",
  "Tarazá",
  "Tarqui",
  "Tarso",
  "Tasco",
  "Tauramena",
  "Tausa",
  "Tame",
  "Tena",
  "Tenerife",
  "Teorama",
  "Teruel",
  "Tesalia",
  "Tibacuy",
  "Tibaná",
  "Tibasosa",
  "Tibú",
  "Timbío",
  "Timbiquí",
  "Tinjacá",
  "Tipacoque",
  "Tiquisio",
  "Titiribí",
  "Toca",
  "Tocaima",
  "Tocancipá",
  "Togüí",
  "Toledo (Antioquia)",
  "Toledo (Norte de Santander)",
  "Tolú",
  "Toluviejo",
  "Tona",
  "Tópaga",
  "Topaipí",
  "Toribío",
  "Toro",
  "Totoró",
  "Trinidad",
  "Trujillo",
  "Tubará",
  "Tuluá",
  "Tunja",
  "Turbaco",
  "Turbaná",
  "Turmequé",
  "Turbo",
  "Tuta",
  "Tutazá",
  "Ubalá",
  "Ubaque",
  "Ulloa",
  "Úmbita",
  "Unguía",
  "Unión Panamericana",
  "Uramita",
  "Uribia",
  "Urrao",
  "Urumita",
  "Usiacurí",
  "Útica",
  "Valdivia",
  "Valle de San José",
  "Valle del Guamuez",
  "Valledupar",
  "Valparaíso (Antioquia)",
  "Valparaíso (Caquetá)",
  "Vegachí",
  "Vélez",
  "Venecia (Antioquia)",
  "Venecia (Cundinamarca)",
  "Venadillo",
  "Ventaquemada",
  "Versalles",
  "Vetas",
  "Vijes",
  "Vigía del Fuerte",
  "Vianí",
  "Villagarzón",
  "Villagómez",
  "Villa Caro",
  "Villa de Leyva",
  "Villa del Rosario",
  "Villa Rica",
  "Villahermosa",
  "Villamaría",
  "Villapinzón",
  "Villarrica",
  "Villanueva (Bolívar)",
  "Villanueva (Casanare)",
  "Villanueva (La Guajira)",
  "Villanueva (Santander)",
  "Villavicencio",
  "Villavieja",
  "Villeta",
  "Viotá",
  "Viracachá",
  "Vista Hermosa",
  "Viterbo",
  "Yacopí",
  "Yacuanquer",
  "Yalí",
  "Yarumal",
  "Yolombó",
  "Yondó",
  "Yotoco",
  "Yumbo",
  "Zambrano",
  "Zapayán",
  "Zaragoza",
  "Zarzal",
  "Zetaquira",
  "Zipacón",
  "Zipaquirá",
  "Zona Bananera",
];
